import './globals.css'
import { Metadata } from "next";
import { Overpass } from "next/font/google";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const overpass = Overpass({ subsets: ['latin'] })

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={"h-screen"}>
        <main className={`${overpass.className} bg-black h-full grid place-items-center px-6`}>
        {children}
        </main>
        </body>
        </html>
    )
}
